#!/usr/bin/env bash
#-*-coding:utf-8-*-
# ******************************************************
# Author       : kaleo
# Last modified: 2017-03-23 10:19
# Email        : kaleo1990@hotmail.com
# Filename     : classtojava
# Description  : 
# ******************************************************
count=0
function convertFileEncode()  
{  
    filename=$1  
    fEncode=$2  
    tEncode=$3  
    t=`file $filename | grep UTF-8 | wc -l`  
    if [ "UTF-8" = $fEncode -a $t -eq 1 ] || [ "UTF-8" = $tEncode -a $t -eq 0 ] ; then  
        iconv -f $fEncode -t $tEncode $i -o $i  
        echo "iconv -f $fEncode -t $tEncode $i -o $i"  
    fi  
}  
function replace(){
    filename=$1
    extension=${filename##*.}
    echo $extension
    if [[ $extension == 'class' ]]
    then
        name=${filename/%class/java}
        rm $filename 
        echo 'delete' $filename
        echo ''>$name
        echo 'create' $name
        count=`expr $count + 1`
    fi
}
function scandir() {
    local cur_dir parent_dir workdir
    workdir=$1
    cd ${workdir}
    if [ ${workdir} = "/" ]
    then
        cur_dir=""
    else
        cur_dir=$(pwd)
    fi

    for dirlist in $(ls ${cur_dir})
    do
        if test -d ${dirlist};then
            cd ${dirlist}
            scandir ${cur_dir}/${dirlist}
            cd ..
        else
            echo ${cur_dir}/${dirlist}
            replace ${cur_dir}/${dirlist}

        fi
    done
}

if [[ $1 != '' ]]
then
    if test -d $1
    then
        scandir $1
    elif test -f $1
    then
        echo "you input a file but not a directory,pls reinput and try again"
        exit 1
    else
        echo "the Directory isn't exist which you input,pls input a new one!!"
        exit 1
    fi
else
    echo "please input dirname"
fi
echo 'replaced: '$count' files'
