#!/usr/bin/env bash
#-*-coding:utf-8-*-
# ******************************************************
# Author       : kaleo
# Last modified: 2017-03-28 00:59
# Email        : kaleo1990@hotmail.com
# Filename     : cptometer
# Description  : 
# ******************************************************
sudo cp $1 /opt/metasploit-framework/embedded/framework/modules/exploits/kaleo/
