#!/usr/bin/env bash
# ******************************************************
# Author       : kaleo
# Last modified: 2017-02-22 14:56
# Email        : kaleo1990@hotmail.com
# Filename     : createtable
# Description  : 
# ******************************************************

php artisan make:migration create_$1_table --create=$1  
