#!/usr/bin/env bash
# ******************************************************
# Author       : kaleo
# Last modified: 2017-02-17 17:26
# Email        : kaleo1990@hotmail.com
# Filename     : filetomysql
# Description  : 
# ******************************************************
if [[ $1 = "" ]]; then
    #statements
    echo "filetomysql filename databasename"
else
echo "truncate keywords;" | mysql -h120.24.159.2 -uroot -pkaleozhou ordersys ;
mysql -h120.24.159.2 -uroot -pkaleozhou ordersys <<eof
load data local infile '$1' into table keywords fields terminated by ',' lines terminated by '\n';
eof
fi


