#!/usr/bin/env bash
# ******************************************************
# Author       : kaleo
# Last modified: 2017-05-03 14:08
# Email        : kaleo1990@hotmail.com
# Filename     : exreset
# Description  : 
# ******************************************************
expressvpn disconnect
expressvpn connect


