#!/usr/bin/env bash
# ******************************************************
# Author       : kaleo
# Last modified: 2017-02-17 17:26
# Email        : kaleo1990@hotmail.com
# Filename     : filetomysql
# Description  : 
# ******************************************************
if [[ $1 = "" || $2 = "" ]]; then
    #statements
    echo "filetomysql filename databasename"
else
mysql <<eof
load data local infile '$1' into table $2 fields terminated by ',' lines terminated by '\n';
eof
fi


