#!/usr/bin/env bash
#-*-coding:utf-8-*-
# ******************************************************
# Author       : kaleo
# Last modified: 2017-04-14 00:17
# Email        : kaleo1990@hotmail.com
# Filename     : tokaleomysql
# Description  : 
# ******************************************************
echo "select plan,groups,keyword,url from ordersys.keywords where url='$1' or keyword='$1'" | mysql -h120.24.159.2 -uroot -pkaleozhou ordersys
