#!/usr/bin/env bash
#-*-coding:utf-8-*-
# ******************************************************
# Author       : kaleo
# Last modified: 2017-04-11 16:54
# Email        : kaleo1990@hotmail.com
# Filename     : uftptobigher
# Description  : 
# ******************************************************
if [[ $1 = "" ]]; then
    filename='041101-fulian.zip'
else
    filename=$1
fi
if [[ $2 = "" ]]; then
    hostname='192.168.60.188'
else
    hostname=$2
fi
scp  bigher@$hostname:/home/bigher/$filename .
