#!/usr/bin/env bash
# ******************************************************
# Author       : kaleo
# Last modified: 2017-05-14 14:39
# Email        : kaleo1990@hotmail.com
# Filename     : gitfromkaleo
# Description  : 
# ******************************************************
git clone git@code.csdn.net:kaleozhou/$1.git
