#!/usr/bin/env bash
# ******************************************************
# Author       : kaleo
# Last modified: 2017-05-22 08:39
# Email        : kaleo1990@hotmail.com
# Filename     : jiami
# Description  : 
# ******************************************************
pass=`getpwd kaleozhou`
zip -P $pass -r kaleo.zip *
echo "encyypt success >> kaleo.zip"
