#!/usr/bin/env bash
# ******************************************************
# Author       : kaleo
# Last modified: 2017-02-17 16:56
# Email        : kaleo1990@hotmail.com
# Filename     : mysqltofile.sh
# Description  : 
# ******************************************************
echo "select * from keywords;" | mysql -h120.24.159.2 -uroot -pkaleozhou ordersys > keyword.csv;
