#!/usr/bin/env bash
# ******************************************************
# Author       : kaleo
# Last modified: 2017-05-14 14:27
# Email        : kaleo1990@hotmail.com
# Filename     : myappinit
# Description  : 
# ******************************************************
./myapp install myapp
./myapp install add
./myapp install caidao
./myapp install checksite
./myapp install daili
./myapp install tokaleo
