#!/usr/bin/env bash
# ******************************************************
# Author       : kaleo
# Last modified: 2017-03-06 10:53
# Email        : kaleo1990@hotmail.com
# Filename     : myhydrassh
# Description  : 
# ******************************************************
hydra -l $1 -p $2 -t 1 -vV -e ns $3 ssh
