#!/usr/bin/env bash
# ******************************************************
# Author       : kaleo
# Last modified: 2017-03-01 17:25
# Email        : kaleo1990@hotmail.com
# Filename     : nm
# Description  : 
# ******************************************************
echo $1
sudo nmap -A $1 >> $2 
