#!/usr/bin/env bash
# ******************************************************
# Author       : kaleo
# Last modified: 2017-03-01 03:02
# Email        : kaleo1990@hotmail.com
# Filename     : mysql_crack
# Description  : 
# ******************************************************
if [ x$1 = x ];
then
#no input
echo "please input hostname:\n"
read hostname
else
	hostname=$1
	
fi
#echo "please input pwname:\n"
#read pwname
 pwname=/home/kaleo/mybash/pwd.txt
echo "crack starting ----"
php /home/kaleo/mybash/mq_crack.php $hostname $pwname>$hostname.txt
echo "crack finshed \n"
cat $hostname.txt
