#!/usr/bin/env bash
#-*-coding:utf-8-*-
# ******************************************************
# Author       : kaleo
# Last modified: 2017-03-25 17:56
# Email        : kaleo1990@hotmail.com
# Filename     : opendb
# Description  : 
# ******************************************************
cd ~/dbeaver
./dbeaver
