#!/usr/bin/env bash
#-*-coding:utf-8-*-
# ******************************************************
# Author       : kaleo
# Last modified: 2017-04-20 14:14
# Email        : kaleo1990@hotmail.com
# Filename     : putto12
# Description  : 
# ******************************************************
ftp -n 120.25.166.88
