#!/usr/bin/env bash
#-*-coding:utf-8-*-
# ******************************************************
# Author       : kaleo
# Last modified: 2017-03-22 20:01
# Email        : kaleo1990@hotmail.com
# Filename     : scptokaleo
# Description  : 
# ******************************************************
scp $1 root@120.24.159.2:/var/www/html/
