#!/usr/bin/env bash
# ******************************************************
# Author       : kaleo
# Last modified: 2017-02-17 15:52
# Email        : kaleo1990@hotmail.com
# Filename     : search
# Description  : 
# ******************************************************
if [  $1 = ""]; then
    #statements
    nohup chromium-browser www.baidu.com
else
    nohup chromium-browser www.baidu.com/s?wd=$1
fi
