#!/usr/bin/env bash
#-*-coding:utf-8-*-
# ******************************************************
# Author       : kaleo
# Last modified: 2017-04-14 00:17
# Email        : kaleo1990@hotmail.com
# Filename     : tokaleomysql
# Description  : 
# ******************************************************
echo "select * from (select * from ordersys.userdatas order by id desc limit 50) tab order by id;" | mysql -h120.24.159.2 -uroot -pkaleozhou ordersys
