#!/usr/bin/env bash
#-*-coding:utf-8-*-
# ******************************************************
# Author       : kaleo
# Last modified: 2017-04-14 00:17
# Email        : kaleo1990@hotmail.com
# Filename     : tokaleomysql
# Description  : 
# ******************************************************
echo 'select * from zb_member where robots=0' | mysql -h106.14.59.186 -uroot -phzdlmwhzb888 mmtvzb.com
echo 'select count(*) from zb_member where robots=0' | mysql -h106.14.59.186 -uroot -phzdlmwhzb888 mmtvzb.com
