#!/usr/bin/env bash
#-*-coding:utf-8-*-
# ******************************************************
# Author       : kaleo
# Last modified: 2017-04-14 00:17
# Email        : kaleo1990@hotmail.com
# Filename     : tokaleomysql
# Description  : 
# ******************************************************
today()
{
    date "+%Y-%m-%d"

}
today=`today`;
echo "select * from userdatas;" | mysql -h120.24.159.2 -uroot -pkaleozhou ordersys
echo "今天注册了："
echo "select count(*) from ordersys.userdatas where created_at>'$today';" | mysql -h120.24.159.2 -uroot -pkaleozhou ordersys
