#!/usr/bin/env bash
#-*-coding:utf-8-*-
# ******************************************************
# Author       : kaleo
# Last modified:	2017-04-30 18:18
# Email        : kaleo1990@hotmail.com
# Filename     :	spoon
# Description  : 
# ******************************************************
cd ~/data-integration
./spoon.sh
