#!/usr/bin/env bash
# ******************************************************
# Author       : kaleo
# Last modified: 2017-03-01 00:36
# Email        : kaleo1990@hotmail.com
# Filename     : sqlm
# Description  : 
# ******************************************************
sqlmap -u $1 -v 1 --dbs
