#!/usr/bin/env bash
# ******************************************************
# Author       : kaleo
# Last modified: 2017-05-21 18:07
# Email        : kaleo1990@hotmail.com
# Filename     : startvnc
# Description  : 
# ******************************************************
x11vnc -auth guess -forever -loop -noxdamage -repeat -rfbauth /home/kaleo/.vnc/passwd -rfbport 5900 -shared
