#!/usr/bin/env bash
#-*-coding:utf-8-*-
# ******************************************************
# Author       : kaleo
# Last modified: 2017-03-31 17:03
# Email        : kaleo1990@hotmail.com
# Filename     : tossh
# Description  : 
# ******************************************************
proxychains4 ssh db2inst1@$1
