#!/usr/bin/env bash
# ******************************************************
# Author       : kaleo
# Last modified: 2017-02-19 11:13
# Email        : kaleo1990@hotmail.com
# Filename     : weixin
# Description  : 
# ******************************************************
nohup webchat


