#!/usr/bin/env bash
# ******************************************************
# Author       : kaleo
# Last modified: 2017-05-17 21:08
# Email        : kaleo1990@hotmail.com
# Filename     : zuocao
# Description  : 
# ******************************************************
xdg-open ~/Videos/ticao.mp4
